apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: docker.io/saket14/sakethelloworld:1.1
        ports:
        - containerPort: 8080